from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.colors import darkgreen


def generate_pdf(
    filename,
    username,
    plant,
    disease,
    confidence,
    prediction_time,
    info,
    severity,
    weather=None
):

    styles = getSampleStyleSheet()

    title = styles["Heading1"]
    title.alignment = TA_CENTER
    title.textColor = darkgreen

    heading = styles["Heading2"]
    normal = styles["BodyText"]

    pdf = SimpleDocTemplate(filename)

    story = []

    # ----------------------------------------------------
    # TITLE
    # ----------------------------------------------------

    story.append(
        Paragraph(
            "🌿 PlantDoctor AI",
            title
        )
    )

    story.append(
        Paragraph(
            "Plant Disease Diagnosis Report",
            heading
        )
    )

    story.append(Spacer(1, 20))

    # ----------------------------------------------------
    # USER DETAILS
    # ----------------------------------------------------

    story.append(Paragraph(f"<b>User:</b> {username}", normal))
    story.append(Paragraph(f"<b>Plant:</b> {plant}", normal))
    story.append(Paragraph(f"<b>Disease:</b> {disease}", normal))
    story.append(
        Paragraph(
            f"<b>Confidence:</b> {confidence*100:.2f}%",
            normal
        )
    )

    story.append(
        Paragraph(
            f"<b>Prediction Time:</b> {prediction_time:.2f} sec",
            normal
        )
    )

    story.append(
        Paragraph(
            f"<b>Severity:</b> {severity}",
            normal
        )
    )

    story.append(Spacer(1, 20))

    # ----------------------------------------------------
    # WEATHER
    # ----------------------------------------------------

    if weather:

        story.append(
            Paragraph("Weather Information", heading)
        )

        story.append(
            Paragraph(
                f"Temperature : {weather['temperature']} °C",
                normal
            )
        )

        story.append(
            Paragraph(
                f"Humidity : {weather['humidity']} %",
                normal
            )
        )

        story.append(
            Paragraph(
                f"Wind Speed : {weather['wind']} km/h",
                normal
            )
        )

        story.append(Spacer(1, 20))

    # ----------------------------------------------------
    # DISEASE DETAILS
    # ----------------------------------------------------

    story.append(Paragraph("Description", heading))
    story.append(Paragraph(info["description"], normal))

    story.append(Spacer(1, 12))

    story.append(Paragraph("Symptoms", heading))
    story.append(Paragraph(info["symptoms"], normal))

    story.append(Spacer(1, 12))

    story.append(Paragraph("Treatment", heading))
    story.append(Paragraph(info["treatment"], normal))

    story.append(Spacer(1, 12))

    story.append(Paragraph("Prevention", heading))
    story.append(Paragraph(info["prevention"], normal))

    story.append(Spacer(1, 30))

    story.append(
        Paragraph(
            "<b>Generated by PlantDoctor AI</b>",
            title
        )
    )

    pdf.build(story)

    return filename